#!/bin/sh

for file in "$@"
do
	height=`mediainfo --Inform="Video;%Height%" "$file"`
	if [ $height -gt 480 ]; then
		out=`echo "$file" | sed -e 's/\.[A-Za-z0-9]*$/.480p.mkv/'`
		if [ -e "$out" ] ; then
			echo "Not overwriting $out"
		else
			echo HandBrakeCLI -i "$file" -o "$out"  -e x264 -q 26 -B 96 --height 480
		fi
	fi
done
