#!/bin/sh

# Recode a video to x264 480p. Saves a copy in a subdirectory "vaxpect".
# Does nothing if the video is already 480p or less.
# Call as
#	env VAXPECT_HEIGHT=720 VAXPECT_Q=23 VAXPECT_AUDIO_BITRATE=160 vaxpect *.mp4
# to encode to a different height or quality.
# x264 quality 26 is acceptable. Increase the value to compact more at
# the expense of quality; lower to 23 or 20 to increase quality but
# with a significant file size increase.

target_hgt=${VAXPECT_HEIGHT:-"480"}
target_q=${VAXPECT_Q:-"26"}
target_br=${VAXPECT_AUDIO_BITRATE:-"96"}
target_codec=${VAXPECT_VIDEO_CODEC:-"x264"}

for file in "$@"
do
	height=`mediainfo --Inform="Video;%Height%" "$file"`
	if [ $height -gt $target_hgt ]; then
		[ -d vaxpect ] || mkdir vaxpect
		#out=`echo "$file" | sed -e 's/\.[A-Za-z0-9]*$/.$target_hgtp.mkv/'`
		out=vaxpect/`echo "$file" | sed -e 's/\.[A-Za-z0-9]*$/.mkv/'`
		if [ -e "$out" ] ; then
			echo "Not overwriting $out"
		else
			HandBrakeCLI -i "$file" -o "$out"  -e $target_codec -q $target_q -B $target_br --height $target_hgt
		fi
	fi
done
